move rust_to_ocaml sources around
Summary:
in D46824721 i added errpy (https://github.com/facebook/errpy/tree/main) to fbsource/third-party/rust [^1] and attempted to use it in the pyre build (errpy vendors ocamlrep packages & tree-sitter-python). it's really close to working!

in particular these targets all build
  buck2 build fbsource//third-party/rust:ocamlrep_ocamlpool-0.0.0-ocamlpool_cpp
  buck2 build fbsource//third-party/rust:ocamlrep_ocamlpool-0.0.0
  buck2 build fbsource//third-party/rust:ocamlrep-0.0.0
  buck2 build fbsource//third-party/rust:ocamlrep_derive-0.0.0
this command is failing though
```
buck2 build fbsource//third-party/rust:rust_to_ocaml_attr-0.0.0
```
with error
```
error: couldn't read buck-out/v2/gen/fbsource/6c6c6022c5181a3c/third-party/rust/___rust_to_ocaml_attr-0.0.0__/__srcs/vendor/rust_to_ocaml_attr-0.0.0/../attr/rust_to_ocaml_attr.rs: No such file or directory (os error 2)
```
i'm pretty sure that this is because of attempts to use `..` paths for sources relative to `Cargo.toml` files. this moves files around so that it is no longer necessary.
[^1]: https://www.internalfb.com/intern/wiki/Rust-at-meta/Third_Party_Libraries/Managing_fbsource_third-party_with_Reindeer/

Reviewed By: rjbailey

Differential Revision: D46881341

fbshipit-source-id: 527d85ac6aa936bb2f8cb21c41b6b54621a79873