Add missing arg
Summary:
```
Error running analysis for `fbcode//tupperware/integrationtests/tests:agent_basic_test (ovr_config//platform/linux:x86_64-fbcode-platform010-clang15#04438cd10a67142f)`: Error running analysis for `fbcode//tupperware/integrationtests/framework:tw_integration_test_mixin (ovr_config//platform/linux:x86_64-fbcode-platform010-clang15#04438cd10a67142f)`: Error running analysis for `fbcode//tupperware/integrationtests/framework:tupperware_setup (ovr_config//platform/linux:x86_64-fbcode-platform010-clang15#04438cd10a67142f)`: Error running analysis for `fbcode//tupperware/integrationtests/framework:resource_allowance_service_setup (ovr_config//platform/linux:x86_64-fbcode-platform010-clang15#04438cd10a67142f)`: Error running analysis for `fbcode//iaas/resource_allowance_system/service:ras_storage (ovr_config//platform/linux:x86_64-fbcode-platform010-clang15#04438cd10a67142f)`: Error running analysis for `fbcode//iaas/resource_allowance_system/allowances:resource_allowance_service_lib (ovr_config//platform/linux:x86_64-fbcode-platform010-clang15#04438cd10a67142f)`: Error running analysis for `fbcode//iaas/reservation_allocator/states_store:rasstore (ovr_config//platform/linux:x86_64-fbcode-platform010-clang15#04438cd10a67142f)`: Error running analysis for `fbcode//manifold/client:manifold_client (ovr_config//platform/linux:x86_64-fbcode-platform010-clang15#04438cd10a67142f)`: Error running analysis for `fbcode//manifold/privacy:enforcement (ovr_config//platform/linux:x86_64-fbcode-platform010-clang15#04438cd10a67142f)`: Error running analysis for `fbcode//privacy/schemas/manifold/schemalib:cpp (ovr_config//platform/linux:x86_64-fbcode-platform010-clang15#04438cd10a67142f)`: Error running analysis for `fbcode//privacylib/lang:singleton-cpp_bindings (ovr_config//platform/linux:x86_64-fbcode-platform010-clang15#04438cd10a67142f)`: Error running analysis for `fbcode//privacylib/lang:singleton-mutual (ovr_config//platform/linux:x86_64-fbcode-platform010-clang15#04438cd10a67142f)`: Error running analysis for `fbcode//privacylib/lang:singleton-singleton.ligen-mutual (ovr_config//platform/linux:x86_64-fbcode-platform010-clang15#04438cd10a67142f)`: Error running analysis for `fbcode//ligen/compiler/codegens/mutual:cli (fbcode//buck2/platform/execution:linux-x86_64#5632a2637af811ac)`: Error running analysis for `fbcode//ligen/compiler/codegens/mutual:mutual_codegen (fbcode//buck2/platform/execution:linux-x86_64#5632a2637af811ac)`: Error running analysis for `fbcode//ligen/compiler:string_formatters (fbcode//buck2/platform/execution:linux-x86_64#5632a2637af811ac)`: Traceback (most recent call last):
  File <builtin>, in <module>
  * fbcode/buck2/prelude/rust/rust_library.bzl:258, in rust_library_impl
      rustdoc_test = generate_rustdoc_test(
  * fbcode/buck2/prelude/rust/build.bzl:257, in generate_rustdoc_test
      get_link_args(
error: Missing parameter `link_style` for call to fbcode/buck2/prelude/linking/link_info.bzl.get_link_args
   --> fbcode/buck2/prelude/rust/build.bzl:257:13
    |
257 |               get_link_args(
    |  _____________^
258 | |                 inherited_non_rust_link_info(ctx, include_doc_deps = True),
259 | |             ),
    | |_____________^
    |

1 BUILDS FAILED
Tests finished: Pass 0. Fail 0. Fatal 0. Skip 0. Build failure 1
```

Reviewed By: markisaa

Differential Revision: D48367728

fbshipit-source-id: 5e3feacaf872a7f30f78ccc2d8fd0b2b9045a752