Copy within_view attributes to the Apple __ResourceBundle_Private
Summary:
Unless we propagate the `visibility` and `within_view` attributes to the target we inject, parent targets that have these attributes will end up failing validation:

```
 error: checking `within_view` for attribute `deps` of `fbsource//xplat/arfx/creation/test_utils/http_server:http_serverTestsAppleMac__ResourceBundle_Private`
         --> fbcode/buck2/prelude/apple/apple_resource_bundle.bzl:76:5
          |
       76 |       apple_resource_bundle_rule(
          |  _____^
       77 | |         name = resource_bundle_name,
       78 | |         **resource_bundle_kwargs
       79 | |     )
          | |_____^
          |

       checking `within_view` for attribute `deps` of `fbsource//xplat/arfx/creation/test_utils/http_server:http_serverTestsAppleMac__ResourceBundle_Private`

       Caused by:
           Dependency `fbsource//xplat/FBPluginFeature:FBPluginFeatureAppleWatchOS` is not within view (as specified by `within_view` attribute):
```

Reviewed By: stepancheg

Differential Revision: D47439253

fbshipit-source-id: 6a4ae5cadaea4f9e8dc1f003a2230a0ec027a65a