Fix doctests in modes that use doctest_link_style=static
Summary:
Previously doctest would fail in our `dbg` and `opt` build modes because we'd be telling rustdoc to link the test binaries and their dependencies with "static" link style, but simultaneously introducing a dependency on the "static_pic" library and all its "static_pic" dependencies (due to DEFAULT_STATIC_LINK_STYLE being "static_pic").

```
---- buck-out/v2/gen/fbcode/cb7c27f2cc10895b/common/rust/shed/futures_stats/__futures_stats__/__srcs/src/futures03.rs - futures03::TimedTryFutureExt::try_timed (line 263) stdout ----
error[E0523]: found two different crates with name `futures_core` that are not distinguished by differing `-C metadata`. This will result in symbol conflicts between the two.
 --> buck-out/v2/gen/fbcode/cb7c27f2cc10895b/common/rust/shed/futures_stats/__futures_stats__/__srcs/src/futures03.rs:266:1
  |
6 | futures::executor::block_on(async {
  | ^^^^^^^

error: aborting due to previous error

Couldn't compile the test.
```

An important alternative to consider is why not just change this line:

https://www.internalfb.com/code/fbsource/[003d058c5e96dcd13ddfaaa13b7149d62109bfb0]/fbcode/buck2/prelude/rust/rust_library.bzl?lines=222%2C226%2C229

```
-    library = rust_param_artifact[static_library_params],
+    library = rust_param_artifact[lang_style_param[(LinkageLang("rust"), doctest_link_style)]],
```

I spent some effort trying to get that to work when doctest_link_style="shared" and wasn't able. I think something in rustdoc just doesn't support being given non-static dependencies, which seems plausible because this is not something Cargo would ever do.

```
---- buck-out/v2/gen/fbcode/b6819c711ba2d5c2/common/rust/shed/futures_stats/__futures_stats__/__srcs/src/futures03.rs - futures03::TimedFutureExt::timed (line 240) stdout ----
Test executable failed (exit status: 127).

stderr:
/data/users/dtolnay/fbsource/buck-out/v2/gen/fbcode/b6819c711ba2d5c2/common/rust/shed/futures_stats/__futures_stats__/rustdoctestYI81eA/rust_out: error while loading shared libraries: libfutures_stats-14f7b3fb.so: cannot open shared object file: No such file or directory
```

Reviewed By: zertosh

Differential Revision: D45218331

fbshipit-source-id: 0e05f300623814be4b23d2c758733c639daae077