Pass rustdoc test command through rustc_action
Summary:
Rustdoc does not support nested `@...` arguments.

```
$ echo 'pub fn f() {}' > lib.rs
$ rustdoc --edition=2021 lib.rs     # success

$ echo '--edition=2021' > args1
$ rustdoc args1 lib.rs             # success

$ echo 'args1' > args2
$ rustdoc args2 lib.rs             # FAIL
error: too many file operands

$ buck2/prelude/rust/tools/rustc_action.py rustdoc args2 lib.rs  # success
```

The rustc_action.py wrapper takes care of opening and flattening every argument that starts with `@`:

https://www.internalfb.com/code/fbsource/[7c821fbc604bca5d1b736f136eb77d72de8ea6a7]/fbcode/buck2/prelude/rust/tools/rustc_action.py?lines=67

and then re-writing them back out as a single flat argsfile to run the command against:

https://www.internalfb.com/code/fbsource/[7c821fbc604bca5d1b736f136eb77d72de8ea6a7]/fbcode/buck2/prelude/rust/tools/rustc_action.py?lines=289-296%2C298-300%2C306

Reviewed By: zertosh

Differential Revision: D52764001

fbshipit-source-id: 3d4774086e579e70bf85e4ecc6ed4e477235983e