Add external debug info on omnibus root provider
Summary:
Fixes missing DWO when a Rust library is the root of an omnibus link.

```
Action failed: fbcode//fblearner/flow/projects/lego:workflow (dwp_omnibus_root libupf_rust_pxl_ref_client_pxl_ref_client.so)
Local command returned non-zero exit code 1
Reproduce locally: `/bin/sh -c "\"\$1\" --continue-on-cu-index-overflow -o \"\$2\" -e \"\$3\" && touch \"\$2\"" "" fbcod ...<omitted>... 46bce1651974e/fblearner/flow/projects/lego/__workflow__/libupf_rust_pxl_ref_client_pxl_ref_client.so`

error: No such file or directory
```

Reviewed By: ayermolo

Differential Revision: D48297167

fbshipit-source-id: ba265587b3b90f8e79caba8e5e5ff9055d2ab092