Make rustc generate DW_AT_comp_dir="." in split debuginfo
Summary:
Rustc's behavior with regard to `DW_AT_comp_dir` and `--remap-path-prefix` is 100% consistent with Clang's `-fdebug-prefix-map`. We only get a `DW_AT_comp_dir` attribute in the Split DWARF skeleton unit if the compilation directory post-mapping is nonempty.

 ---

`echo 'void f() {}' > lib.c; clang-15 -c lib.c -o lib.o -g -gsplit-dwarf -gdwarf-5 -fdebug-prefix-map=$(pwd)= && llvm-dwarfdump lib.o`

**-fdebug-prefix-map=$(pwd)=**

```
0x00000014: DW_TAG_skeleton_unit
              DW_AT_stmt_list	(0x00000000)
              DW_AT_str_offsets_base	(0x00000008)
              DW_AT_GNU_pubnames	(true)
              DW_AT_dwo_name	("lib.dwo")
              DW_AT_low_pc	(0x0000000000000000)
              DW_AT_high_pc	(0x0000000000000006)
              DW_AT_addr_base	(0x00000008)
```

**-fdebug-prefix-map=$(pwd)=.**

```
0x00000014: DW_TAG_skeleton_unit
              DW_AT_stmt_list	(0x00000000)
              DW_AT_str_offsets_base	(0x00000008)
              DW_AT_comp_dir	(".")
              DW_AT_GNU_pubnames	(true)
              DW_AT_dwo_name	("lib.dwo")
              DW_AT_low_pc	(0x0000000000000000)
              DW_AT_high_pc	(0x0000000000000006)
              DW_AT_addr_base	(0x00000008)
```

 ---

`echo 'pub fn f() {}' > lib.rs; rustc lib.rs -o lib.rlib --crate-type lib -Cdebuginfo=2 -Csplit-debuginfo=unpacked -Zdwarf-version=5 --remap-path-prefix=$(pwd)= && llvm-dwarfdump lib.rlib`

**--remap-path-prefix=$(pwd)=**

```
0x00000014: DW_TAG_skeleton_unit
              DW_AT_stmt_list	(0x00000000)
              DW_AT_str_offsets_base	(0x00000008)
              DW_AT_dwo_name	("lib.lib.c897e63a5755c35e-cgu.0.rcgu.dwo")
              DW_AT_low_pc	(0x0000000000000000)
              DW_AT_high_pc	(0x0000000000000001)
              DW_AT_addr_base	(0x00000008)
```

**--remap-path-prefix=$(pwd)=.**

```
0x00000014: DW_TAG_skeleton_unit
              DW_AT_stmt_list	(0x00000000)
              DW_AT_str_offsets_base	(0x00000008)
              DW_AT_comp_dir	(".")
              DW_AT_dwo_name	("lib.lib.c897e63a5755c35e-cgu.0.rcgu.dwo")
              DW_AT_low_pc	(0x0000000000000000)
              DW_AT_high_pc	(0x0000000000000001)
              DW_AT_addr_base	(0x00000008)
```

 ---

Some tools expect that `DW_AT_comp_dir` must be present in units of type `DW_TAG_skeleton_unit` if `DW_AT_dwo_name` is a relative path. For example BOLT crashes if it is not present:

```
llvm-bolt: /data/sandcastle/boxes/trunk-grepo-llvm-c2/llvm-project/bolt/lib/Rewrite/DWARFRewriter.cpp:567:
auto llvm::bolt::DWARFRewriter::updateDebugInfo()::(anonymous class)::operator()(llvm::DWARFUnit &, llvm::bolt::DIEBuilder &, llvm::DIE &) const:
Assertion `CompDirAttrInfo && "DW_AT_comp_dir is not in Skeleton CU."' failed.
```

I checked the 21 places that `DW_AT_comp_dir` is mentioned in https://dwarfstd.org/doc/DWARF5.pdf and none of them explain what it is supposed to mean if `DW_AT_comp_dir` is a relative path.

I found https://dwarfstd.org/issues/210628.1.html titled *"Clarification of relative paths in DW_AT_comp_dir"* which has been accepted for DWARF 6. It adds the following normative text:

> "If a relative path is used in DW_AT_comp_dir, it will be relative to the location of the linked image containing the DW_AT_comp_dir entry."

By this definition, in the future we might need to use a DW_AT_comp_dir path like "../../../../../../../../../../../.." depending on how deeply nested inside the project root the output .rlib or .a is being written...

 ---

I tested that this diff does not regress Rust compiler diagnostics. In particular we don't get "--> ./fbcode/path/to/lib.rs" in error messages. I am not sure of anything this diff affects other than debuginfo.

```
$ buck2 build fbcode//scripts/rust_foundation/arc_rust_fixtures/broken_dep:broken

error[E0412]: cannot find type `broken` in this scope
 --> fbcode/scripts/rust_foundation/arc_rust_fixtures/broken_dep/broken.rs:3:6
  |
3 | impl broken {}
  |      ^^^^^^ not found in this scope
```

Reviewed By: zertosh

Differential Revision: D48219285

fbshipit-source-id: dc208b4dfcf3403108b9a38bbffdde6580c83e3c