replace anymap with anymap3
Summary:
[#136764](https://github.com/rust-lang/rust/pull/136764) breaks the [`anymap`](https://github.com/chris-morgan/anymap) crate via:
```
error[E0804]: cannot add auto traits `Send` and `Sync` to dyn bound via pointer cast
   --> third-party/rust/vendor/anymap-1.0.0-beta.2/src/any.rs:37:40
    |
19  | / macro_rules! impl_clone {
20  | |     ($t:ty) => {
21  | |         impl Clone for Box<$t> {
22  | |             #[inline]
...   |
37  | |                 unsafe { Box::from_raw(raw as *mut $t) }
    | |                                        ^^^^^^^^^^^^^^ unsupported cast
...   |
48  | | }
    | |_- in this expansion of `impl_clone!`
...
145 |   impl_clone!(dyn CloneAny + Send + Sync);
    |   --------------------------------------- in this macro invocation
    |
    = note: this could allow UB elsewhere
    = help: use `transmute` if you're sure this is sound

```
Since `anymap` is not maintained any more, switching everyone to a fork that is i.e. [`anymap3`](https://github.com/reivilibre/anymap3) which also solves the above using the suggested `transmute`.

Reviewed By: jsgf

Differential Revision: D75098213

fbshipit-source-id: dace0feaca2960508c57d02d229c4a32747ba588