Accept the prelude TARGETS file isn't Buck1 compatible
Summary:
This file isn't compatible with Buck1 already:

```
ndmitchell@ndmitchell-mbp buck2 % buck1 targets prelude//:
Downloading buck...
[======================================================================]
Restarting Buck daemon because Buck version has changed...
Buck daemon started.
ERROR: /Users/ndmitchell/fbsource/fbcode/buck2/prelude/native.bzl:436:39: name '__internal__' is not defined
Cannot parse /Users/ndmitchell/fbsource/fbcode/buck2/prelude/native.bzl
```

So stop pretending it is.

Reviewed By: IanChilds

Differential Revision: D49047909

fbshipit-source-id: 52c58dee919672a02287c4bb06690cb507fd2337