Unbreak :fat_platform_incompatible
Summary:
```
BUILD FAILED
Error running analysis for `prelude//platforms:default (<unbound>)`

Caused by:
    0: Error looking up configured node prelude//platforms:default (<unbound>)
    1: looking up unconfigured target node `prelude//platforms:default`
    2: Error loading targets in package `prelude//platforms` for target `prelude//platforms:default`
    3: Error evaluating build file: `prelude//platforms:BUCK`
    4: Traceback (most recent call last):
         * tools/buck/prelude/platforms/BUCK:31, in <module>
             export_file(
         * tools/buck/prelude/native.bzl:209, in _export_file_macro_stub
             __rules__["export_file"](name = name, src = name if src == None else src, **k...
       error: Error coercing attribute `src` of `prelude//platforms:fat_platform_incompatible`
          --> tools/buck/prelude/native.bzl:209:5
           |
       209 |     __rules__["export_file"](name = name, src = name if src == None else src, **kwargs)
           |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           |

       Error coercing attribute `src` of `prelude//platforms:fat_platform_incompatible`

       Caused by:
           0: Error coercing attribute `src` of type `attrs.option(attrs.source(), default=None)`
           1: Error coercing "TARGETS.v2"
           2: Couldn't coerce `TARGETS.v2` as a source.
                Error when treated as a target: Invalid absolute target pattern `TARGETS.v2` is not allowed: Expected a `:`, a trailing `/...` or the literal `...`.
                Error when treated as a path: Source file `TARGETS.v2` does not exist as a member of package `prelude//platforms`.
```

Reviewed By: zertosh

Differential Revision: D50631075

fbshipit-source-id: 189577e548109bd2641a1695b7f69e74e1417625