Make "debuginfo" subtarget of C++ executable dependable upon
Summary:
There is a …[debuginfo] subtarget on C++ rules, for example, `fbcode//hphp/hhvm:hhvm_link[debuginfo]`, which is documented as *"Provide a debug info target to make sure debug info is materialized."*

Unfortunately it's not usable for BOLT because it used `DefaultInfo.other_outputs`. "Other outputs" are outputs that are materialized only if you build the target directly, not if you depend on the target from a different rule.

https://www.internalfb.com/code/fbsource/[b970bc926874745d1c681e248b4aa61beb765bee]/fbcode/buck2/app/buck2_build_api/src/interpreter/rule_defs/provider/builtin/default_info.rs?lines=127-130

https://www.internalfb.com/code/fbsource/[b970bc926874745d1c681e248b4aa61beb765bee]/fbcode/buck2/app/buck2_build_api/src/interpreter/rule_defs/provider/builtin/default_info.rs?lines=131-136

This diff replaces `other_outputs` with something that *is* able to be depended upon. HHVM's run_bolt.sh requires the external debug info available, so it needs a target it can depend on that materializes all the relevant debug info. This is implemented in {D48139947}.

Note: `default_outputs = project_artifacts(ctx.actions, [external_debug_info])` would be the naive fix here. However, it doesn't type-check, even though `default_outputs` and `other_outputs` have the same type in the snippets above. Seems like this is the difference between "list of Artifact" vs "list of ArtifactTraversable".

```
Error running analysis for `fbcode//hphp/hhvm:hhvm_link (ovr_config//platform/linux:x86_64-fbcode-platform010-clang-split-dwarf#83d6cf51b6d767a3)`

error: Type of parameter `default_outputs` doesn't match
   --> fbcode/buck2/prelude/cxx/cxx_executable.bzl:587:33
    |
587 |       sub_targets["debuginfo"] = [DefaultInfo(
    |  _________________________________^
588 | |         default_outputs = project_artifacts(ctx.actions, [external_debug_info]),
589 | |     )]
    | |_____^
    |
```

Reviewed By: christycylee, shayne-fletcher

Differential Revision: D48143267

fbshipit-source-id: a1c43f14a5d39fe6905b1889e5dc306b89d788c5